name: Test
on: [push, pull_request]
jobs:
  node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [6, 8, 10, 12, 14, 16]
    name: Node ${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install
        run: npm install
      - name: Test
        run: npm test
  browser:
    runs-on: ubuntu-latest
    name: Browsers
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install
        run: npm install
      - name: Install playwright dependencies
        run: npx playwright install-deps
      - name: Test
        run: npm run test-browsers-local
